"""Skill Generator: Convert MethodSpec into a structured skill directory."""
import json
import os
import logging
from dataclasses import dataclass, asdict

logger = logging.getLogger(__name__)

SKILL_MD_TEMPLATE = """# {name}

{summary}

## Description
{description}

## Category
{category}

## Usage
Use when working with {category}-related tasks involving {name_lower}.
Triggers on: "{triggers}"

## Key Equations
{equations}

## Hyperparameters
{hyperparams}

## Inputs/Outputs
**Inputs:**
{inputs}

**Outputs:**
{outputs}

## Dependencies
{dependencies}

## Validation
- **Benchmarks:** {benchmarks}
- **Metrics:** {metrics}

## References
- [{paper_title}]({paper_url}) ({year})

---

*Auto-generated by Paper-to-Skill Pipeline on {date}*
"""

SCRIPT_TEMPLATE = '''"""
Implementation of {name} based on the original paper.

Reference: [{paper_title}]({paper_url})
"""
import math
import torch
import torch.nn as nn
import torch.nn.functional as F


{implementation}
'''

VALIDATION_SCRIPT_TEMPLATE = '''"""
Validation tests for {name} implementation.
"""
import torch
import sys
sys.path.insert(0, '.')

from method import *

def test_basic():
    """Test basic forward pass."""
    print("Testing basic forward pass...")
    {test_code}
    print("✓ Basic test passed")

if __name__ == "__main__":
    test_basic()
    print("All tests passed!")
'''


def generate_skill_md(spec: dict) -> str:
    """Generate SKILL.md content from MethodSpec dict."""
    eqs = spec.get("key_equations", [])
    equations = "\n".join(f"- `{eq}`" for eq in eqs) if eqs else "None extracted"
    
    hyperparams = spec.get("hyperparameters", [])
    hp_str = "\n".join(f"- **{hp['name']}**: {hp['description']} (default: {hp.get('default_value', 'N/A')})" for hp in hyperparams) if hyperparams else "See paper for details"
    
    inputs = spec.get("inputs", [])
    in_str = "\n".join(f"- `{inp['name']}` ({inp['type']}): {inp['description']}" for inp in inputs) if inputs else "See paper for input specification"
    
    outputs = spec.get("outputs", [])
    out_str = "\n".join(f"- `{out['name']}` ({out['type']}): {out['description']}" for out in outputs) if outputs else "See paper for output specification"
    
    deps = spec.get("depends_on", [])
    dep_str = ", ".join(deps) if deps else "None specified"
    
    benchmarks = ", ".join(spec.get("benchmark_datasets", [])) or "See paper"
    metrics = ", ".join(spec.get("evaluation_metrics", [])) or "See paper"
    
    name = spec.get("name", "Unknown Method")
    triggers = name.lower() + ", " + spec.get("category", "").replace("_", " ")
    
    return SKILL_MD_TEMPLATE.format(
        name=name,
        summary=spec.get("summary", ""),
        description=spec.get("description", "")[:1000],
        category=spec.get("category", ""),
        name_lower=name.lower(),
        triggers=triggers,
        equations=equations,
        hyperparams=hp_str,
        inputs=in_str,
        outputs=out_str,
        dependencies=dep_str,
        benchmarks=benchmarks,
        metrics=metrics,
        paper_title=spec.get("paper_title", ""),
        paper_url=spec.get("paper_url", ""),
        year=spec.get("year", ""),
        date="2026-04-11",
    )


def generate_method_script(spec: dict) -> str:
    """Generate Python implementation script from MethodSpec."""
    name = spec.get("name", "Method")
    equations = spec.get("key_equations", [])
    
    # Generate a skeleton implementation
    impl_lines = []
    impl_lines.append(f"class {name.replace(' ', '').replace('-', '')}Module(nn.Module):")
    impl_lines.append(f'    """Implementation of {name}."""')
    impl_lines.append(f"    def __init__(self):")
    impl_lines.append(f"        super().__init__()")
    impl_lines.append(f"        # TODO: Initialize parameters based on paper")
    impl_lines.append(f"    ")
    impl_lines.append(f"    def forward(self, x):")
    impl_lines.append(f"        # TODO: Implement forward pass based on paper")
    impl_lines.append(f"        return x")
    impl_lines.append("")
    
    # Add equation comments
    for eq in equations:
        impl_lines.append(f"# Equation: {eq}")
    
    implementation = "\n".join(impl_lines)
    
    return SCRIPT_TEMPLATE.format(
        name=name,
        paper_title=spec.get("paper_title", ""),
        paper_url=spec.get("paper_url", ""),
        implementation=implementation,
    )


def generate_validation_script(spec: dict) -> str:
    """Generate validation/test script."""
    name = spec.get("name", "Method")
    test_code = "model = MethodModule()\n    x = torch.randn(2, 10)\n    out = model(x)\n    assert out.shape[0] == 2"
    
    return VALIDATION_SCRIPT_TEMPLATE.format(
        name=name,
        test_code=test_code,
    )


def generate_skill_directory(spec: dict, output_dir: str):
    """Generate a complete skill directory."""
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, "scripts"), exist_ok=True)
    os.makedirs(os.path.join(output_dir, "references"), exist_ok=True)
    
    # SKILL.md
    skill_md = generate_skill_md(spec)
    with open(os.path.join(output_dir, "SKILL.md"), 'w') as f:
        f.write(skill_md)
    logger.info(f"Generated SKILL.md")
    
    # Method implementation
    method_script = generate_method_script(spec)
    with open(os.path.join(output_dir, "scripts", "method.py"), 'w') as f:
        f.write(method_script)
    logger.info(f"Generated scripts/method.py")
    
    # Validation script
    val_script = generate_validation_script(spec)
    with open(os.path.join(output_dir, "scripts", "validate.py"), 'w') as f:
        f.write(val_script)
    logger.info(f"Generated scripts/validate.py")
    
    # Save spec as reference
    with open(os.path.join(output_dir, "references", "method_spec.json"), 'w') as f:
        json.dump(spec, f, indent=2)
    logger.info(f"Generated references/method_spec.json")
    
    # README
    readme = f"# {spec.get('name', 'Generated Skill')}\n\nAuto-generated skill from paper-to-skill pipeline.\n\nSee SKILL.md for full details.\n"
    with open(os.path.join(output_dir, "README.md"), 'w') as f:
        f.write(readme)
    
    logger.info(f"Skill directory generated at {output_dir}")


if __name__ == "__main__":
    from synthesizer import synthesize_from_content
    from extractor import parse_markdown_paper, content_to_dict
    
    sample = """# Attention Is All You Need

## Abstract
We propose a new simple network architecture, the Transformer, based solely on attention mechanisms.

## 3 Model Architecture
The Transformer follows an encoder-decoder structure.

$$\\text{Attention}(Q, K, V) = \\text{softmax}(\\frac{QK^T}{\\sqrt{d_k}})V$$
"""
    content = parse_markdown_paper(sample, url="arxiv.org/abs/1706.03762")
    spec = synthesize_from_content(content_to_dict(content))
    
    import tempfile
    out = tempfile.mkdtemp(prefix="p2s_test_")
    generate_skill_directory(asdict(spec), out)
    print(f"Generated skill at {out}")
    
    with open(os.path.join(out, "SKILL.md")) as f:
        print(f.read()[:1000])
